allow_agent: true
compress: true
gss_auth: false
gss_deleg_creds: false
gss_host: eiger.alps.cscs.ch
gss_kex: false
key_filename: /home/pizzi/.ssh/cscs-key
key_policy: RejectPolicy
load_system_host_keys: true
look_for_keys: true
port: 22
proxy_command: ''
proxy_jump: ela.cscs.ch
safe_interval: 10.0
timeout: 60
use_login_shell: true
username: pizzi
